language: rust
rust:
  - stable
  - nightly
before_install:
  - bash check-style.sh
script:
  - cd server && cargo build --verbose && cd ..
  - cd server && cargo test --verbose && cd ..
  - cargo build --verbose
  - cargo test --verbose
after_success:
  - |
        test ${TRAVIS_PULL_REQUEST} == "false" && \
        test ${TRAVIS_BRANCH} == "master" && \
        test "${TRAVIS_BUILD_NUMBER}.1" == "${TRAVIS_JOB_NUMBER}" && \
        bash deploy-docs.sh
